// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ex2.proto

/*
Package ex2 is a generated protocol buffer package.

It is generated from these files:
	ex2.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	FibMsg
*/
package ex2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FibMsg struct {
	Num int64 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
}

func (m *FibMsg) Reset()                    { *m = FibMsg{} }
func (m *FibMsg) String() string            { return proto.CompactTextString(m) }
func (*FibMsg) ProtoMessage()               {}
func (*FibMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FibMsg) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "ex2.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "ex2.HelloResponse")
	proto.RegisterType((*FibMsg)(nil), "ex2.FibMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/ex2.Hello/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ex2.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ex2.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex2.proto",
}

// Client API for Fibonacci service

type FibonacciClient interface {
	Fib(ctx context.Context, in *FibMsg, opts ...grpc.CallOption) (*FibMsg, error)
}

type fibonacciClient struct {
	cc *grpc.ClientConn
}

func NewFibonacciClient(cc *grpc.ClientConn) FibonacciClient {
	return &fibonacciClient{cc}
}

func (c *fibonacciClient) Fib(ctx context.Context, in *FibMsg, opts ...grpc.CallOption) (*FibMsg, error) {
	out := new(FibMsg)
	err := grpc.Invoke(ctx, "/ex2.Fibonacci/Fib", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fibonacci service

type FibonacciServer interface {
	Fib(context.Context, *FibMsg) (*FibMsg, error)
}

func RegisterFibonacciServer(s *grpc.Server, srv FibonacciServer) {
	s.RegisterService(&_Fibonacci_serviceDesc, srv)
}

func _Fibonacci_Fib_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FibMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FibonacciServer).Fib(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ex2.Fibonacci/Fib",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FibonacciServer).Fib(ctx, req.(*FibMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fibonacci_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ex2.Fibonacci",
	HandlerType: (*FibonacciServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fib",
			Handler:    _Fibonacci_Fib_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ex2.proto",
}

func init() { proto.RegisterFile("ex2.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xad, 0x30, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0xad, 0x30, 0x52, 0x52, 0xe2, 0xe2, 0xf1, 0x48,
	0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb9, 0x78, 0xa1,
	0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13,
	0xd3, 0x61, 0xea, 0x60, 0x5c, 0x25, 0x29, 0x2e, 0x36, 0xb7, 0xcc, 0x24, 0xdf, 0xe2, 0x74, 0x21,
	0x01, 0x2e, 0xe6, 0xbc, 0xd2, 0x5c, 0xb0, 0x3c, 0x73, 0x10, 0x88, 0x69, 0x64, 0xc3, 0xc5, 0x0a,
	0x36, 0x46, 0xc8, 0x98, 0x8b, 0x23, 0x38, 0xb1, 0x12, 0xc2, 0x16, 0xd4, 0x03, 0x39, 0x08, 0xd9,
	0x09, 0x52, 0x42, 0xc8, 0x42, 0x10, 0x1b, 0x95, 0x18, 0x8c, 0xf4, 0xb8, 0x38, 0xdd, 0x32, 0x93,
	0xf2, 0xf3, 0x12, 0x93, 0x93, 0x33, 0x85, 0x14, 0xb9, 0x98, 0xdd, 0x32, 0x93, 0x84, 0xb8, 0xc1,
	0x2a, 0x21, 0x16, 0x4a, 0x21, 0x73, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x9e, 0x34, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x90, 0xd3, 0x67, 0xf0, 0xf1, 0x00, 0x00, 0x00,
}
